version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - restore_cache:
          keys:
        # when lock file changes, use increasingly general patterns to restore cache
            - myapp-{{ checksum "package-lock.json" }}
           

      - checkout
      - run: ls
      - run: pwd

      
      - run:
          name: Run tests
          command: npm run test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: myapp-{{ checksum "package-lock.json" }}  
          
      


   
