version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.10.0
    steps:
<<<<<<< HEAD
      - checkout      
      - run:
 
          name: "Setup custom environment variables // its your workflow step"
 
          command: |
 
            echo 'export LT_USERNAME="shubhamsaini4006"' >> $BASH_ENV
 
      - run:
 
          name: "Setup custom environment variables"
 
          command: |
 
            echo 'export LT_ACCESS_KEY="{JM8vmhqFvnmjDNiVjfRbciwqoKrOH8d9CzC37kTkRajjaaOPGH}"' >> $BASH_ENV
 
      - run: # Validating your above mentioned environment variables
 
          name: "Here is the LT_Username : "
 
          command: echo ${LT_USERNAME}
      
=======
      - restore_cache:
          keys:
        # when lock file changes, use increasingly general patterns to restore cache
            - myapp-{{ checksum "package-lock.json" }}
           

      - checkout
      - run: ls
      - run: pwd
      - run: npm install

      
      - run:
          name: Run tests
          command: npm run test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: myapp-{{ checksum "package-lock.json" }}  
>>>>>>> e022fd94421a7405108e8eb569a702b05c3e2cd8
          
      


   
