version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout      
      - run:
 
          name: "Setup custom environment variables // its your workflow step"
 
          command: |
 
            echo 'export LT_USERNAME="shubhamsaini4006"' >> $BASH_ENV
 
      - run:
 
          name: "Setup custom environment variables"
 
          command: |
 
            echo 'export LT_ACCESS_KEY="{JM8vmhqFvnmjDNiVjfRbciwqoKrOH8d9CzC37kTkRajjaaOPGH}"' >> $BASH_ENV
 
      - run: # Validating your above mentioned environment variables
 
          name: "Here is the LT_Username : "
 
          command: echo ${LT_USERNAME}
      
          
      


   
